### ISSUE TITLE
Cost Forecast metrics

### ISSUE THREAD

**Issue by artful88533** [electrolux-oss/aws-cost-exporter#19]
Hello!
First of all, thank you for creating such a great tool!
I was wondering if it would be possible to add metrics for cost forecasts for the current month (using GetCostForecast)
Having alerts based on forecasted information would be incredibly helpful.

**Comment by gluckzhang** [comment]
Hi @artful88533, sorry I have been on vacation and missed this message. It sounds like a great idea :)

As there is an API to get the forecasts, it is definitely possible to fetch it and expose it as a metric. I will take a look after the vacation. At the same time, you or other users are more than welcome to contribute to this feature! 🚀

**Comment by gluckzhang** [comment]
Got it, thanks for the updates @artful88533! We will still consider adding the forecast metrics for the exporter later on, it is a good idea :) I am going to close this issue for now.
